"""
Script: move_scanned_cvs.py
Purpose:
    - Moves scanned CVs (flagged as "SCANNED PDF") from the 'raw_cvs' folder to the 'scanned_cvs' folder.
    - Uses the log file ('cv_scan_check.log') generated by the 'detect_cvs.py' script.

Key Features:
    - Reads the log file to identify scanned CVs.
    - Ensures the destination folder exists.
    - Moves scanned CVs to the 'scanned_cvs' folder.

Dependencies:
    - shutil
    - pathlib

Usage:
    - Run the script after generating the log file using 'detect_scanned_cvs.py'.
"""

import shutil
from pathlib import Path

# Define paths
base_dir = Path("C:/Users/PC/Desktop/Nsayblik_Internship/Freelancer-AI-system")
raw_cvs_dir = base_dir / "data/raw_cvs"  # Source folder for raw CVs
scanned_dir = base_dir / "data/scanned_cvs"  # Destination folder for scanned CVs
log_file = base_dir / "logs/cv_scan_check.log"  # Log file containing scan results

# Create scanned_cvs directory if it doesn't exist
scanned_dir.mkdir(parents=True, exist_ok=True)

# Move scanned one-page PDFs based on log file
with open(log_file, "r", encoding="utf-8") as f:
    for line in f:
        if line.strip().endswith("SCANNED PDF"):  # Identify scanned CVs from log file
            filename = line.split()[0]  # Extract filename from log line
            src = raw_cvs_dir / filename  # Source path
            dst = scanned_dir / filename  # Destination path
            if src.exists():
                shutil.move(str(src), str(dst))  # Move file to scanned_cvs folder
                print(f"Moved: {filename}")
            else:
                print(f"File not found: {filename}")  # Handle missing files
